apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: poc-test 
build:
  tagPolicy:
    gitCommit: {}
  local: {}
  artifacts:
    - image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test 

deploy:
  kubectl:
    manifests:
      - ./k8s/*.yaml 
  logs:
    prefix: container 
 
profiles:
  - name: target-1 
    build:
      artifacts:
       - image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test 
