apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: poc-test # Name of your application
build:
  tagPolicy:
    gitCommit: {} # This defines how your images are tagged
  local: {} # Local builds, can be removed if you're not using them
  artifacts:
    - image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test:${_SHORT_SHA} # Uncommented and fixed image path

deploy:
  kubectl:
    manifests:
      - ./k8s/*.yaml # Path to your Kubernetes manifests
  logs:
    prefix: container # Fixed the prefix indentation
 
profiles:
  - name: target-1 # Define the profile here
    build:
      artifacts:
         - image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test:${_SHORT_SHA} # Example specific to this profile
      # cache:
        # disabled: true # Disable caching for global builds

#skaffold 