apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-test
  labels:
    app: poc-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-test
  template:
    metadata:
      labels:
        app: poc-test
    spec:
      containers:
        - name: poc-test
          image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test:v7
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"s
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
