apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-test
  labels:
    app: poc-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-test
  template:
    metadata:
      labels:
        app: poc-test
    spec:
      containers:
        - name: poc-test
<<<<<<< HEAD
          image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test:${_IMAE_TAG} # Update with your image
=======
          image: us-central1-docker.pkg.dev/poc-test-447813/poc-test/poc-test:latest
>>>>>>> 0aab1ee4c8262594a58a5565eec8d4ad3871ace1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          # env:
          #   - name: GIT_COMMIT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: git-commit
          #         key: sha # Update with your image