apiVersion: v1
kind: Service
metadata:
  name: poc-test
spec:
  selector:
    app: poc-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Use NodePort if you're not using a cloud load balancer
